# Redefine Gentrification

In this project, our team analyzed a data set consisting of low-cost housing sales in urban communities across the United States. Using the data we predicted the cost to revamp a given urban neighborhood across the U.S. 

Our mission is to provide each community with the financial cost of redeveloping from within and preventing gentrification by big businesses.

In [10]:
# Import the required libraries 
import pandas as pd
import requests
import os 
from pathlib import Path
import hvplot.pandas

In [11]:
# Created a DataFrame using the read_csv function and Path module
nyc_avg_price = pd.read_csv("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=969&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=AVELISPRI35620&scale=left&cosd=2016-07-01&coed=2022-03-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2022-04-30&revision_date=2022-04-30&nd=2016-07-01")

# Clean up the DataFrame
nyc_avg_price.set_index(['DATE'], inplace=True)
nyc_avg_price.rename(columns={'AVELISPRI35620' : 'New York City'}, inplace=True)

# Review the DataFrame
nyc_avg_price

            New York City
DATE
2016-07-01       901204.0
2016-08-01       889390.0
2016-09-01       904550.0
2016-10-01       938805.0
2016-11-01       982640.0
...                   ...
2021-11-01      1557436.0
2021-12-01      1631077.0
2022-01-01      1713536.0
2022-02-01      1699961.0
2022-03-01      1700187.0

[69 rows x 1 columns]

In [12]:
# Created a DataFrame using the read_csv function and Path module
atl_avg_price = pd.read_csv("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=969&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=AVELISPRI12060&scale=left&cosd=2016-07-01&coed=2022-03-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2022-04-30&revision_date=2022-04-30&nd=2016-07-01")

# Clean up the DataFrame
atl_avg_price.set_index(['DATE'], inplace=True)
atl_avg_price.rename(columns={'AVELISPRI12060' : 'Atlanta'}, inplace=True)

# Review the DataFrame
atl_avg_price

             Atlanta
DATE
2016-07-01  388666.0
2016-08-01  378985.0
2016-09-01  380813.0
2016-10-01  381728.0
2016-11-01  384815.0
...              ...
2021-11-01  544044.0
2021-12-01  538092.0
2022-01-01  545479.0
2022-02-01  566392.0
2022-03-01  568445.0

[69 rows x 1 columns]

In [13]:
# Created a DataFrame using the read_csv function and Path module
sf_avg_price = pd.read_csv("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=969&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=AVELISPRI41860&scale=left&cosd=2016-07-01&coed=2022-03-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2022-04-30&revision_date=2022-04-30&nd=2016-07-01")

# Clean up the DataFrame
sf_avg_price.set_index(['DATE'], inplace=True)
sf_avg_price.rename(columns={'AVELISPRI41860' : 'San Francisco'}, inplace=True)

# Review the DataFrame
sf_avg_price

            San Francisco
DATE
2016-07-01      1250159.0
2016-08-01      1191156.0
2016-09-01      1237716.0
2016-10-01      1299805.0
2016-11-01      1301761.0
...                   ...
2021-11-01      1795658.0
2021-12-01      1842466.0
2022-01-01      1746953.0
2022-02-01      1747732.0
2022-03-01      1732109.0

[69 rows x 1 columns]

In [14]:
# Created a DataFrame using the read_csv function and Path module
la_avg_price = pd.read_csv("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=969&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=AVELISPRI31080&scale=left&cosd=2016-07-01&coed=2022-03-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2022-04-30&revision_date=2022-04-30&nd=2016-07-01")

# Clean up the DataFrame
la_avg_price.set_index(['DATE'], inplace=True)
la_avg_price.rename(columns={'AVELISPRI31080' : 'Los Angeles'}, inplace=True)

# Review the DataFrame
la_avg_price

            Los Angeles
DATE
2016-07-01    1419470.0
2016-08-01    1386776.0
2016-09-01    1396414.0
2016-10-01    1413883.0
2016-11-01    1442889.0
...                 ...
2021-11-01    2176716.0
2021-12-01    2299565.0
2022-01-01    2438265.0
2022-02-01    2473989.0
2022-03-01    2411312.0

[69 rows x 1 columns]

In [15]:

# Created a DataFrame using the read_csv function and Path module
dc_avg_price = pd.read_csv("https://fred.stlouisfed.org/graph/fredgraph.csv?bgcolor=%23e1e9f0&chart_type=line&drp=0&fo=open%20sans&graph_bgcolor=%23ffffff&height=450&mode=fred&recession_bars=on&txtcolor=%23444444&ts=12&tts=12&width=969&nt=0&thu=0&trc=0&show_legend=yes&show_axis_titles=yes&show_tooltip=yes&id=AVELISPRI11001&scale=left&cosd=2016-07-01&coed=2022-03-01&line_color=%234572a7&link_values=false&line_style=solid&mark_type=none&mw=3&lw=2&ost=-99999&oet=99999&mma=0&fml=a&fq=Monthly&fam=avg&fgst=lin&fgsnd=2020-02-01&line_index=1&transformation=lin&vintage_date=2022-04-30&revision_date=2022-04-30&nd=2016-07-01")

# Clean up the DataFrame
dc_avg_price.set_index(['DATE'], inplace=True)
dc_avg_price.rename(columns={'AVELISPRI11001' : 'District of Columbia'}, inplace=True)

# Review the DataFrame
dc_avg_price

            District of Columbia
DATE
2016-07-01              874528.0
2016-08-01              850013.0
2016-09-01              855633.0
2016-10-01              867678.0
2016-11-01              875827.0
...                          ...
2021-11-01              897894.0
2021-12-01              904985.0
2022-01-01              902651.0
2022-02-01              931818.0
2022-03-01              946968.0

[69 rows x 1 columns]

In [16]:
# Join NYC, ATL, SF, LA, DC average prices into single DataFrame with columns for each
combined_avg_prices = pd.concat([nyc_avg_price, atl_avg_price, sf_avg_price, la_avg_price, dc_avg_price], axis="columns", join="inner")

# Review Combined DataFrame
combined_avg_prices

,New York City,Atlanta,San Francisco,Los Angeles,District of Columbia
DATE,,,,,
2016-07-01,901204.0,388666.0,1250159.0,1419470.0,874528.0
2016-08-01,889390.0,378985.0,1191156.0,1386776.0,850013.0
2016-09-01,904550.0,380813.0,1237716.0,1396414.0,855633.0
2016-10-01,938805.0,381728.0,1299805.0,1413883.0,867678.0
2016-11-01,982640.0,384815.0,1301761.0,1442889.0,875827.0
...,...,...,...,...,...
2021-11-01,1557436.0,544044.0,1795658.0,2176716.0,897894.0
2021-12-01,1631077.0,538092.0,1842466.0,2299565.0,904985.0
2022-01-01,1713536.0,545479.0,1746953.0,2438265.0,902651.0
2022-02-01,1699961.0,566392.0,1747732.0,2473989.0,931818.0
2022-03-01,1700187.0,568445.0,1732109.0,2411312.0,946968.0

In [17]:
# Created line plot for the average price per city

combined_avg_prices_plot = combined_avg_prices.hvplot.line(
    xlabel= "Date",
    ylabel= "Average Price",
    title= "Average Prices Per City",
    rot=90,
    frame_width= 950,
    frame_height= 500
)

combined_avg_prices_plot

:NdOverlay   [Variable]
   :Curve   [DATE]   (value)