In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("https://econdata.s3-us-west-2.amazonaws.com/Reports/Core/RDC_Inventory_Core_Metrics_State_History.csv")
df

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202203,wisconsin,wi,331500.0,0.0443,0.1515,4574.0,-0.0127,-0.1693,47.0,...,429688.0,0.0466,0.0692,11357.0,0.0570,-0.1518,1.4779,0.1587,0.0460,0.0
1,202203,west virginia,wv,184000.0,0.0363,0.1500,2182.0,-0.0259,-0.2522,64.0,...,312938.0,-0.0335,0.2420,4468.0,0.0166,-0.1851,1.0587,0.1015,0.1796,0.0
2,202203,alaska,ak,387450.0,0.0516,0.1869,733.0,0.0209,-0.3676,43.0,...,475211.0,0.0321,0.1532,817.0,0.0394,-0.3577,0.1187,0.0240,0.0221,0.0
3,202203,michigan,mi,241950.0,0.0638,-0.0320,10505.0,0.0001,-0.0702,39.0,...,377418.0,0.0220,-0.0337,19260.0,0.0125,-0.0974,0.8334,0.0225,-0.0570,0.0
4,202203,arizona,az,477871.0,0.0157,0.1948,6774.0,-0.0135,0.0538,33.0,...,778763.0,0.0269,0.0719,23022.0,-0.0138,-0.0302,2.4082,0.0086,-0.2776,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3516,201607,minnesota,mn,241900.0,NaN,NaN,26217.0,NaN,NaN,60.0,...,335434.0,NaN,NaN,40240.0,NaN,NaN,0.5218,NaN,NaN,NaN
3517,201607,arkansas,ar,163000.0,NaN,NaN,18771.0,NaN,NaN,88.0,...,222943.0,NaN,NaN,21628.0,NaN,NaN,0.1529,NaN,NaN,NaN
3518,201607,texas,tx,279900.0,NaN,NaN,99575.0,NaN,NaN,60.0,...,406689.0,NaN,NaN,142549.0,NaN,NaN,0.4281,NaN,NaN,NaN
3519,201607,alabama,al,189500.0,NaN,NaN,32634.0,NaN,NaN,89.0,...,254685.0,NaN,NaN,34539.0,NaN,NaN,0.0575,NaN,NaN,NaN
3520,quality_flag = 1: year-over-year figures may ...,please contact economics@realtor.com for more...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df2 = pd.read_csv("https://econdata.s3-us-west-2.amazonaws.com/Reports/Core/RDC_Inventory_Core_Metrics_County_History.csv")
df2

,month_date_yyyymm,county_fips,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag
0,202203,2068,"denali, ak",320000.0,0.0702,-0.4019,1.0,0.0000,-0.6667,8.0,...,320000.0,0.0702,-0.0303,1.0,0.0000,-0.6667,NaN,NaN,NaN,1.0
1,202203,13273,"terrell, ga",78000.0,-0.0764,-0.2334,8.0,-0.1111,-0.3846,89.0,...,103433.0,-0.7978,-0.2223,8.0,-0.2727,-0.3846,NaN,NaN,NaN,1.0
2,202203,2180,"nome, ak",250000.0,NaN,NaN,0.0,NaN,NaN,6.0,...,250000.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0
3,202203,8061,"kiowa, co",120000.0,0.3333,0.0000,2.0,1.0000,1.0000,862.0,...,88500.0,0.1800,-0.1128,2.0,0.0000,0.0000,NaN,NaN,NaN,1.0
4,202203,20203,"wichita, ks",70000.0,-0.0667,-0.0667,1.0,0.0000,0.0000,117.0,...,70000.0,-0.0667,-0.0667,1.0,-0.5000,0.0000,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213692,201607,20047,"edwards, ks",64900.0,NaN,NaN,3.0,NaN,NaN,178.0,...,67575.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
213693,201607,16077,"power, id",120000.0,NaN,NaN,50.0,NaN,NaN,114.0,...,144880.0,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN
213694,201607,54071,"pendleton, wv",165000.0,NaN,NaN,32.0,NaN,NaN,93.0,...,187659.0,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,NaN
213695,201607,38071,"ramsey, nd",174999.0,NaN,NaN,6.0,NaN,NaN,79.0,...,174953.0,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN
213696,quality_flag = 1: year-over-year figures may ...,please contact economics@realtor.com for more...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df2.count()

month_date_yyyymm                          213697
county_fips                                213697
county_name                                213696
median_listing_price                       213666
median_listing_price_mm                    176395
median_listing_price_yy                    175563
active_listing_count                       213666
active_listing_count_mm                    176309
active_listing_count_yy                    175429
median_days_on_market                      213696
median_days_on_market_mm                   176416
median_days_on_market_yy                   175581
new_listing_count                          213669
new_listing_count_mm                       150863
new_listing_count_yy                       150220
price_increased_count                      213669
price_increased_count_mm                    49471
price_increased_count_yy                    50006
price_reduced_count                        213669
price_reduced_count_mm                     137514
price_reduced_count_yy                     140419
pending_listing_count                      192120
pending_listing_count_mm                   157284
pending_listing_count_yy                   149131
median_listing_price_per_square_foot       213211
median_listing_price_per_square_foot_mm    176079
median_listing_price_per_square_foot_yy    175051
median_square_feet                         213211
median_square_feet_mm                      176079
median_square_feet_yy                      175051
average_listing_price                      213666
average_listing_price_mm                   176395
average_listing_price_yy                   175563
total_listing_count                        213669
total_listing_count_mm                     176431
total_listing_count_yy                     175551
pending_ratio                              192116
pending_ratio_mm                           158676
pending_ratio_yy                           151638
quality_flag                               176746
dtype: int64